FROM openjdk:11-jdk AS jdk

FROM python:3.9

USER root

# --------------------------------------------------------
# JAVA
# --------------------------------------------------------
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
    software-properties-common \
    python3-launchpadlib \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Add OpenJDK from the previous stage
COPY --from=jdk /usr/local/openjdk-11 /usr/lib/jvm/java-11-openjdk-arm64/
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64/
ENV PATH=$JAVA_HOME/bin:$PATH

# --------------------------------------------------------
# HADOOP
# --------------------------------------------------------
ENV HADOOP_VERSION=3.3.6
ENV HADOOP_HOME=/opt/hadoop-$HADOOP_VERSION
ENV HADOOP_CONF_DIR=/etc/hadoop
ENV HADOOP_URL=https://downloads.apache.org/hadoop/common/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz

RUN set -e \
    && curl -fSL "$HADOOP_URL" -o /tmp/hadoop.tar.gz \
    && tar -xvf /tmp/hadoop.tar.gz -C /opt/ \
    && rm /tmp/hadoop.tar.gz \
    && ln -s /opt/hadoop-$HADOOP_VERSION/etc/hadoop /etc/hadoop \
    && mkdir /opt/hadoop-$HADOOP_VERSION/logs /hadoop-data

COPY conf/core-site.xml $HADOOP_CONF_DIR/core-site.xml
COPY conf/hdfs-site.xml $HADOOP_CONF_DIR/hdfs-site.xml
COPY conf/mapred-site.xml $HADOOP_CONF_DIR/mapred-site.xml
COPY conf/yarn-site.xml $HADOOP_CONF_DIR/yarn-site.xml

# --------------------------------------------------------
# SPARK
# --------------------------------------------------------
ENV SPARK_VERSION=spark-3.5.1
ENV SPARK_HOME=/opt/$SPARK_VERSION
ENV SPARK_URL=https://downloads.apache.org/spark/$SPARK_VERSION/$SPARK_VERSION-bin-hadoop3.tgz

RUN set -e \
    && curl -fSL "$SPARK_URL" -o /tmp/spark.tar.gz \
    && tar -xvzf /tmp/spark.tar.gz -C /opt/ \
    && mv /opt/$SPARK_VERSION-bin-hadoop3 /opt/$SPARK_VERSION \
    && rm /tmp/spark.tar.gz \
    && ln -s /opt/$SPARK_VERSION/etc/hadoop $SPARK_HOME/conf

# --------------------------------------------------------
# INSTALL PYTHON DEPS
# --------------------------------------------------------
RUN apt-get update \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    build-essential \
    libopenblas-dev \
    liblapack-dev \
    redis-tools \
    xvfb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ADD requirements.txt /requirements.txt
RUN pip install --default-timeout=100 --upgrade pip \
    && pip install Cython numpy setuptools \
    && pip install -r /requirements.txt

# Set up entrypoint
ADD entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]