services:
  spark-master:
    image: spark-base:3.5.0
    container_name: spark-master
    ports:
      - "9090:8081"
      - "7077:7077"
    volumes:
      - /bigdata/spark/apps:/opt/spark-apps
      - /bigdata/spark/data:/opt/spark-data
      - ./spark/conf/log4j.properties:/opt/bitnami/spark/conf/log4j.properties
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./spark/jars_dir:/opt/spark/ivy:z
    networks:
      - hadoop_network
    command: /bin/sh -c "./start-spark.sh"

  spark-worker-1:
    image: spark-base:3.5.0
    container_name: spark-worker-1
    ports:
      - "9091:8081"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=8G
      - SPARK_DRIVER_MEMORY=4G
      - SPARK_EXECUTOR_MEMORY=2G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-1
    volumes:
      - /bigdata/spark/apps:/opt/spark-apps
      - /bigdata/spark/data:/opt/spark-data
      - ./spark/conf/log4j.properties:/opt/bitnami/spark/conf/log4j.properties
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./spark/jars_dir:/opt/spark/ivy:z
    networks:
      - hadoop_network
    command: /bin/sh -c "./start-spark.sh"

  spark-worker-2:
    image: spark-base:3.5.0
    container_name: spark-worker-2
    ports:
      - "9092:8081"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=8G
      - SPARK_DRIVER_MEMORY=4G
      - SPARK_EXECUTOR_MEMORY=2G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-2
    volumes:
      - /bigdata/spark/apps:/opt/spark-apps
      - /bigdata/spark/data:/opt/spark-data
      - ./spark/conf/log4j.properties:/opt/bitnami/spark/conf/log4j.properties
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./spark/jars_dir:/opt/spark/ivy:z
    networks:
      - hadoop_network
    command: /bin/sh -c "./start-spark.sh"

  livy_server:
    build: ./livy/
    restart: always
    container_name: livy_server
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    environment:
      - SPARK_MASTER_ENDPOINT=spark-master
      - SPARK_MASTER_PORT=7077
      - DEPLOY_MODE=client
    healthcheck:
      test: [ "CMD", "nc", "-z", "livy", "8998" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - ./livy/conf/:/opt/bitnami/livy/conf/
      - /bigdata/livy/target/:/target/
      - /bigdata/livy/data/:/data/
    ports:
      - '8998:8998'
    networks:
      - hadoop_network
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2

# volumes:
#   spark_apps:
#           driver: local-persist
#           driver_opts:
#                mountpoint: /bigdata/spark/apps
#   spark_data:
#           driver: local-persist
#           driver_opts:
#                mountpoint: /bigdata/spark/data

networks:
  hadoop_network:
    name: hadoop_network
    external: true