\connect postgres;

CREATE USER hive;
ALTER USER hive WITH PASSWORD 'hive';
CREATE DATABASE metastore;
GRANT ALL PRIVILEGES ON DATABASE metastore TO hive;

CREATE USER postgres;
ALTER USER postgres WITH PASSWORD 'postgres';
CREATE DATABASE postgres;
GRANT ALL PRIVILEGES ON DATABASE postgres TO postgres;

CREATE USER hueuser;
ALTER USER hueuser WITH PASSWORD 'hue12!';
CREATE DATABASE huedb;
GRANT ALL PRIVILEGES ON DATABASE huedb TO hueuser;